GET http://localhost:3001/api/persons
###
GET https://fso-render-r9io.onrender.com/api/persons

###

GET http://localhost:3001/api/persons/812

###

POST https://fso-render-r9io.onrender.com/api/persons
Content-Type: application/json

{
    "name": "NAME HERE",
    "number": "1-123-457-789"
}

### 
DELETE https://fso-render-r9io.onrender.com/api/persons/963