
GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/812

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "NAME HERE",
    "number": "1-123-457-789"
}

### 
DELETE http://localhost:3001/api/persons/1674